#!/usr/bin/perl
my $SRCDIR = shift;
my $HEAD = shift;
my $TAIL = shift;
unlink $HEAD;
unlink $TAIL;
open(my $fh_tail, '>', $TAIL);
open(my $fh_head, '>', $HEAD);
print $fh_tail "#if HAVE_GNUC_ATTRIBUTE\n";
my $last;
while (my $filename = shift) {
    open (HEADER, $filename) or die("Unable to open $filename");
    while (<HEADER>) {
        if (/^(Fc[^ ]*) \(.*$/) {
            my $name = $1;
            if ($name ne "FcCacheDir" and $name ne "FcCacheSubdir") {
                my $alias="IA__$name";
                my $hattr="__attribute((visibility(\"hidden\")))";
                print $fh_head "extern __typeof ($name) $alias $hattr;\n";
                print $fh_head "#define $name $alias\n";
                my $command="grep -l \"^".$name."[ \(]\" \"$SRCDIR/*.c\"";
                my $ifdef=`$command`;
                $ifdef =~ s/\s+$//;
                $ifdef ne "" or die("error: could not locate $name in src/*.c");
                $ifdef =~ s/.*\/([^.]*)\.c/__\1__/;
                if ($ifdef ne $last) {
                    if (defined $last) { print $fh_tail "#endif /* $last */"."\n"; }
                    print $fh_tail "#ifdef $ifdef\n";
                    $last=$ifdef;
                }
                print $fh_tail "# undef $name\n";
                my $cattr="__attribute((alias(\"'$alias'\"), visibility(\"default\")))";
                print $fh_tail "extern __typeof ($name) $name $cattr;\n";
            }
        }
    }
}
print $fh_tail "#endif /* $ifdef */"."\n";
print $fh_tail "#endif /* HAVE_GNUC_ATTRIBUTE */"."\n";